
services:
  app:
    build: .
    volumes:
      - .:/app
      - static-data:/app/staticfiles  # Statik fayllar uchun
      - media-data:/app/media  # Media fayllar uchun
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
  redis:
        image: redis:7.2-alpine
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data

  celery:
        build:
          context: .
          dockerfile: Dockerfile
        command: celery -A config worker --pool=solo --loglevel=info
        volumes:
          - .:/app
        depends_on:
          - redis
          - app
        environment:
          - PYTHONUNBUFFERED=1


  nginx:
    image: nginx:latest
    ports:
      - "100:100"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-data:/app/staticfiles  # Statik fayllar
      - media-data:/app/media  # Media fayllar (agar kerak bo‘lsa)
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-data:
  media-data:
